<?php
require_once __DIR__ . '/../controllers/controller_view_Condominio.php';

// GERENCIADOR DE PAGINAS :
switch ($DadosGet['pg']){
    case 42 :
        ?>     
        <style type="text/css">
            .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus{background: #3175AF; color: #fff}
        </style>
        <div class="panel panel-primary">
            <div class="panel-heading "></div>
            <div class="panel-body">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#menu1"> [ Condominio ] </a></li>
                    <li><a data-toggle="tab" href="#menu3"> [ Lista / condominio ]</a></li>
                </ul>
                <div class="tab-content">
                    <div id="menu1" class="tab-pane fade in active">
                        <?php  require_once __DIR__ . './formularios/frm_cadastraCondominio.php';?>
                        <?php   
                            if($idCondominio){
                                require_once __DIR__ . './formularios/frm_cadastraServicos.php';
                                require_once __DIR__ . './listas/lst_servicos.php';
                            }
                        ?>
                    </div>
                    <div id="menu3" class="tab-pane fade">
                        <?php  require_once __DIR__ . './listas/lst_condominios.php' ;//LISTA DE PLANILHA DE COMISSÕES ?>
                    </div>    
                </div>    
            </div>
        </div>
        <?php      
    break;
    case 45 :
    ?>     
        <div class="panel panel-primary">
            <div class="panel-heading ">Cadastro de Antena :</div>
            <div class="panel-body">
                <?php  require_once __DIR__ . './formularios/frm_cadastroAntenas.php';?>
                <?php  
                    if(!isset($DadosGet['idA'])){
                        require_once __DIR__ . './listas/lst_antenas.php' ;
                    }
                ?>
            </div>
        </div>
        <?php      
    break;
}